### ISSUE TITLE
Add reference and comment for the new Sendai Framework paper

### ISSUE THREAD

**Issue by bermud** [opengeospatial/health-white-paper#1]
The paper **The Sendai Framework for Disaster Risk Reduction and Its Indicators—Where Does Health Fit in?**  has just been published
http://link.springer.com/article/10.1007/s13753-017-0120-2

Suggested by Virginia Murray 2017.05.24

**Comment by bermud** [comment]
Eddie suggested (May 17, 2017, at 1:32 AM) this relevant points

Some relevant points that are raised (extracts):
ON P.4  The three landmark agreements ﬁnalized in 2015—the
Sustainable Development Goals (United Nations 2015),
the Paris Climate Agreement (UNFCC 2015), and the
Sendai Framework for Disaster Risk Reduction
2015–2030 (UNISDR 2015)—directly address impacts on
health.
 
ON P.3: Many of the Sendai indicators are health-related. Within
Target A, for example, an indicator measures the number of
deaths attributed to disasters, while an indicator in Target B
measures the number of injured or ill people attributed to
disasters. Within Target D, the numbers of health facilities
damaged or destroyed, as well as the disruptions to health
services attributed to disasters are to be measured.
 
ON P.3: Nevertheless, indicators are not without their limitations.
Their measurement often relies on robust and complete data,
which may not be available across all countries, resulting in
comparability issues. Moreover, indicators have the potential
to be misleading, if the data, assumptions, or analyses
behind them are incorrect. Aggregated data, for example,
may mask inequalities within vulnerable groups that, unless
disaggregated, will remain hidden to policymakers. In the
extreme, this can lead to a phenomenon known as Simpson’s
paradox, where a body of data displays a trend, yet when the
data are broken into subgroups, the opposite trend is
apparent for different subgroups (Wagner 1982).
 
ON P.4:  Each of these systems faces a number of common data
collection challenges. Baseline data may not be available, and
there may be a lack of comparable disaster damage and loss
data due to differences in data recording and standards over
time and across countries (European JRC 2015).    
 
ON P.4: The World Health Organization’s Global Reference List of 100
Core Health Indicators aims to contribute to greater alignment
between countries on the reporting of health trends
(WHO 2015). A new edition that takes account of the
Sustainable Development Goals indicators, including those
linked to the Sendai Framework, is due for publication in
2017.

**Comment by serich** [comment]
I made some local white paper edits addressing this issue, but I'm encountering some difficulty getting the modifications pushed into GitHub. Just wanted to insert a comment into the record just in case anybody else is also considering modifications based on this issue. In the meantime I'll continue to try to debug my local problem.
