### ISSUE TITLE
Update Chapter 7 data privacy and  de-identification

### ISSUE THREAD

**Issue by bermud** [opengeospatial/health-white-paper#10]
Section 7.1:

Data Anonymization in the US healthcare system means patient de-identification.  We may need to add that in this bullet. 

Section 7.3:

The data privacy and protection section will need to address legal issues in data sharing, such as patient consent, and the implication that otherwise public data (e.g., weather data) may need to become protected data when it is associated with a patient medical record.  Patient medical records are protected data in most Western countries.

From Ajay Gupta 2017.05.23

**Comment by serich** [comment]
Added bullet to "data-considerations.adoc" describing de-identification guidance for protecting patient health information under the U.S. Federal HIPAA Act.

Added a parenthetical comment to the "data privacy and protection" bullet under "Functional areas recommendations".
