### ISSUE TITLE
Add reference and comment to Global Burden of Disease 

### ISSUE THREAD

**Issue by bermud** [opengeospatial/health-white-paper#2]
First published in 1993, the Global Burden of Disease (GBD) [Study](http://www.healthdata.org/gbd) is a comprehensive regional and global research programme assessing mortality and disability incidence across major diseases, injuries, and risk factors. Currently the programme is based out of the Institute for Health Metrics and Evaluation ([IHME](http://www.healthdata.org/about)) at the University of Washington in Seattle, USA and is funded by the Bill and Melinda Gates Foundation (funding is for 10 years from Jan 2017 and is $279 million). GBD offers significant utility and empowerment for policymakers internationally with critical data on trends in health. The program’s wealth of data is provided through rigorous measurement and analysis mechanisms, and made available through platforms including [GBD’s Visualization Hub](https://vizhub.healthdata.org/gbd-compare/) and has close links to Ministries/Departments of Health and the World Health Organisation. It is described as a consistent and comparative description of the burden of diseases and injuries and the risk factors that cause them is an important input to health decision-making and planning processes. GBD’s globally accepted method of assessment includes categorization of deaths and disability adjusted live years due to a breadth of causes

In the era of understanding disasters heralded by Sendai, the GBD programme offers a global platform for disaster risk reduction to coordinate efforts on loss data, prioritise areas for action, and engage all UN member states. There is a significant opportunity to collaborate to develop a strand in the GBD work to reflect more clearly the needs identified in the Sendai Framework Global Targets A and B.

Suggested by Virginia Murray 2017.05.24

**Comment by serich** [comment]
I couldn't find references to any particular publications other than the three web pages cited in the language in Luis's comment. So I just paraphrased that content, including the hyperlinks to IHME, GBD, and the visualization hub.
