### ISSUE TITLE
Add reference and comment to The Lancet Countdown - tracking health and climate change

### ISSUE THREAD

**Issue by bermud** [opengeospatial/health-white-paper#3]
Add reference and comment to The Lancet Countdown: tracking progress on health and climate change

The Lancet Countdown: tracking progress on health and climate change is an international, multidisciplinary research collaboration between academic institutions and practitioners across the world. It follows on from the work of the 2015 Lancet Commission, which concluded that the response to climate change could be “the greatest global health opportunity of the 21st century”. The Lancet Countdown aims to track the health impacts of climate hazards; health resilience and adaptation; health co-benefits of climate change mitigation; economics and finance; and political and broader engagement. These focus areas form the five thematic working groups of the Lancet Countdown and represent different aspects of the complex association between health and climate change. These thematic groups will provide indicators for a global overview of health and climate change; national case studies highlighting countries leading the way or going against the trend; and engagement with a range of stakeholders. The Lancet Countdown ultimately aims to report annually on a series of indicators across these five working groups. This paper outlines the potential indicators and indicator domains to be tracked by the collaboration, with suggestions on the methodologies and datasets available to achieve this end. The proposed indicator domains require further refinement, and mark the beginning of an ongoing consultation process—from November, 2016 to early 2017—to develop these domains, identify key areas not currently covered, and change indicators where necessary. This collaboration will actively seek to engage with existing monitoring processes, such as the UN Sustainable Development Goals and WHO’s climate and health country profiles. The indicators will also evolve over time through ongoing collaboration with experts and a range of stakeholders, and be dependent on the emergence of new evidence and knowledge. During the course of its work, the Lancet Countdown will adopt a collaborative and iterative process, which aims to complement existing initiatives, welcome engagement with new partners, and be open to developing new research projects on health and climate change.

Suggested by Virginia Murray 2017.05.24

**Comment by serich** [comment]
Added text to "climate-health.adoc" linking to the Lancet Countdown home page and indicating that the working groups and indicators could be a potential source of organizing principles for an SDI or the framework.
