### ISSUE TITLE
Add reference and comment to INFORM

### ISSUE THREAD

**Issue by bermud** [opengeospatial/health-white-paper#4]
INFORM is a global, open-source risk assessment for humanitarian crises and disasters. It can support decisions about prevention, preparedness and response. 

http://www.inform-index.org/

Data and calculation steps
http://www.inform-index.org/Results/Global

Suggested by Virginia Murray 2017.05.24

**Comment by serich** [comment]
Added language to "global-indicators.adoc", including hyperlinks to the INFORM home page and the "Data and calculation steps" page.
