### ISSUE TITLE
Add health systems as stakeholders in Chapter 1

### ISSUE THREAD

**Issue by bermud** [opengeospatial/health-white-paper#5]
We should consider adding Health Systems as a stakeholder.  Ultimately, a health-related framework will have to be adopted by health systems (hospitals and providers) for it to actually be in use.  I’d suggest adding the following:

Health Systems – to understand how a Health Spatial Information Framework can contribute to clinician point-of-care decision support, and be leverage to improve outcomes. 

From Ajay Gupta 2017.05.23

**Comment by serich** [comment]
Add "Health Systems" to "1-summary.adoc".
