### ISSUE TITLE
Add data analytics to 1st Paragraph Chapter  2

### ISSUE THREAD

**Issue by bermud** [opengeospatial/health-white-paper#6]
1st Paragraph in Chapter 2 , suggest adding this as the new last sentence:   

There is also not a defined framework for how to use geospatial data analytics to derive potential solutions to population health challenges.  That is a missing link towards which this white paper hopes to serve as a first step.

From Ajay Gupta 2017.05.23

**Comment by serich** [comment]
Added new last sentence to "intro-background.adoc".
