### ISSUE TITLE
Restate sentence about Doctors 4th Paragraph Chapter 2

### ISSUE THREAD

**Issue by bermud** [opengeospatial/health-white-paper#8]
Chapter 2 - 4th Paragraph, 2nd sentence: 

Doctors due understand geography, weather, and environmental factors when treating asthma, allergies, etc.  I suggest we restate this sentence:  [I realize this needs some cleaning up]

“Health professionals rarely have consistent access to climate and weather data for diagnosing, treating, monitoring, or advising a patient.  While it is recognized by the medical community that the environmental factors these data sources represent do can impact health outcomes for a wide range of patient conditions, partially including asthma, allergies, depression, skin conditions, etc., these data sources not available with the same consistence and accuracy of other health data, such as lab results and patient vital signs, complicating provider efforts to leverage this data to take informed action, or to determine causal relationships over various spatial and temporal scales.” 

From Ajay Gupta 2017.05.23

**Comment by serich** [comment]
Added paraphrased language to "intro-background.adoc".
