### ISSUE TITLE
4th Paragraph, last sentence, adding consistency

### ISSUE THREAD

**Issue by bermud** [opengeospatial/health-white-paper#9]
4th Paragraph, last sentence, suggest adding ‘consistency’ as follows:

“The data challenge includes several aspects:  quantity of data, consistency of data availability, ability to customize data to meet diverse provider requirements, distributed nature of data, the heterogeneity and diversity of the data, the lack of data sharing due to both policy and technology limitations, and difficulties to share across disciplines, organizations, and geographic boundaries.” 

From Ajay Gupta 2017.05.23

**Comment by serich** [comment]
Modified language in "intro-background.adoc".
